admin/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('Shome', views.adminhome),
    path('', views.admin),
    path('create_user', views.create_user),
    path('display_user', views.display_user),
    path('update_user', views.update_user),
    path('delete_user', views.delete_user),
    path('add_category', views.add_category),
    path('display_category', views.display_category),
    path('update_category', views.update_category),
    path('delete_category', views.delete_category),
    path('add_product', views.add_product),
    path('display_product', views.display_product),
    path('update_product', views.update_product),
    path('delete_product', views.delete_product),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import *
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home', views.home),
    path('profile', views.profile),
    path('edit_profile', views.edit_profile),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("my-cart/managecart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("my-cart/emptycart/", EmptyCartView.as_view(), name="emptycart"),
    path("emptycart/", EmptyCartView.as_view(), name="emptycart"),
    path("productdetails",views.productdetails),

    path("my-cart/checkout/", CheckoutView.as_view(), name="checkout"),
    path("paypalpay/", views.Paypalpay),
    path("paypalpay/success/", views.success),
    path("orders/", views.orders),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

urlpatterns = urlpatterns + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from accounts.models import *

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Cancelled", "Order Cancelled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("PayPal", "PayPal"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    u_id = models.CharField(max_length=200, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/addtocart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add to cart</title>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Float four columns side by side */
        .column {
            float: left;
            width: 25%;
            padding: 0 10px;
        }

        /* Remove extra left and right margins, due to padding */
        .row {
            margin: 0 -5px;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive columns */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
                display: block;
                margin-bottom: 20px;
            }
        }

        /* Style the counter cards */
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            padding: 16px;
            text-align: center;
            background-color: #f1f1f1;
        }

        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            width: 300px;
            height: 400px;
            max-height: 400px;
            max-width: 300px;
            margin: auto;
            text-align: center;
            padding: 2px;
            background-color: aliceblue;
        }

        .price {
            color: grey;
            font-size: 22px;
        }

        .card button {
            border: none;
            outline: 0;
            padding: 12px;
            color: white;
            background-color: snow;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

        .card button:hover {
            opacity: 0.7;
        }

        body {
            background-color: whitesmoke;
        }

        .flex-container {
               display: flex;
               justify-content: space-around;
           }

        .show-cart li {
            display: flex;
        }

        .card {
            margin-bottom: 20px;
        }

        .card-img-top {
            width: 200px;
            height: 200px;
            align-self: center;
        }
    </style>
</head>
<body>
    <h1 style="text-align: center;">Product added to Cart</h1>
    <br>
     <li style="color: gainsboro"><a href="/my-cart"> View Cart </a></li>
    <li><a href="/home">click here to go back</a></li>

    <!--<div class="container" style="background-color: white">
    <div class="column">
        <div class="row">
            {% for product in products %}
                <div class="col">
                    <div class="card" style="width: 20rem;">
                        <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
                        <div class="card-block">
                            <h4 class="card-title">{{ product.name }}</h4>
                            <h4 class="warning"></h4>
                            <p class="card-text">{{ product.price }}</p>
                            <a href="add-to-cart-{{product.id}}" data-name="{{ product.name }}" data-price="{{ product.price }}"
                               data-quantity="{{ product.quantity }}" data-id="{{ product.id }}"
                               class="add-to-cart btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div> -->
</body>
</html>

templates/adminlogin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css">
    <style>
        .divider:after,
        .divider:before {
            content: "";
            flex: 1;
            height: 1px;
            background: #eee;
        }
    </style>
</head>

<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex align-items-center justify-content-center h-100">
                <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                    <form>
                        {% csrf_token %}
                        <!-- Email input -->
                        <div class="form-outline mb-4">
                            <input type="email" id="form1Example13" name="email"
                                class="form-control form-control-lg email" />
                            <label class="form-label" for="form1Example13">Email address</label>
                            <p class="emailtest" style="font-weight: bold;color: red;"></p>
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-4">
                            <input type="password" id="form1Example23" name="password"
                                class="form-control form-control-lg password" />
                            <label class="form-label" for="form1Example23">Password</label>
                            <p class="passtest" style="font-weight: bold;color: red;"></p>
                        </div>


                        <!-- Submit button -->
                        <button type="button" id="bttn" class="btn btn-dark btn-lg btn-block">Login</button>
                        <br>
                        <p class="credtest" style="font-weight: bold;color: red;"></p>

                    </form>
                </div>
            </div>
        </div>
    </section>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $('#bttn').click(() => {
        $('.emailtest').text("")
        $('.passtest').text("")
        var email = $('.email').val()
        var password = $('.password').val()
        var data = {
            'csrfmiddlewaretoken': '{{csrf_token}}',
            'email': email,
            'password': password
        }

        if (email == '' && password == '') {
            $('.emailtest').text("Email field must not be empty")
            $('.passtest').text("Password field must not be empty")
        } else if (email == '') {
            $('.emailtest').text("Email field must not be empty")
        } else if (password == '') {
            $('.passtest').text("Password field must not be empty")
        } else {
            $.ajax({
                url: '/adminlogin',
                method: 'POST',
                data: data,
                dataType: 'json',
                success: (data) => {
                    if (data.success) {
                        window.location.replace('/adminpage')
                    } else {
                        $('.credtest').text("Invalid Credentials")
                    }
                }
            })
        }
    })
</script>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
{#    sign- up#}


* {box-sizing: border-box}

/* Full-width input fields */
  input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
    width: 100%;
  }
}
{#home#}

    * {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: indianred;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

.col-25 {
  float: left;
  width: 25%;
  margin-top: 6px;
}

.col-75 {
  float: left;
  width: 75%;
  margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .col-25, .col-75, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}

{#table#}
table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 8px;
}

 /* logout*/
            /* Set a style for all buttons */
            button {
                background-color: #04AA6D;
                color: white;
                padding: 14px 20px;
                margin: 8px 0;
                border: none;
                cursor: pointer;
                width: 100%;
            }

            /* Add a hover effect for buttons */
            button:hover {
                opacity: 0.8;
            }

            .logoutbtn {
                width: auto;
                padding: 10px 18px;
                background-color: #f44336;
            }

            .container {
                padding: 16px;
            }
tr:nth-child(even){background-color: #f2f2f2}
</style>

</head>
<body>

</body>
{%block content%}
    {%endblock%}
</html>

templates/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Checkout</title>
<style>
    body{
        background-color: gainsboro;
    }
    div{
        background-color: snow;
        margin: 30px;
    }

    input {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        box-sizing: border-box;
    }
</style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3><u>Items in the cart</u></h3>
            <a href="/my-cart">Update Cart</a>
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>

                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </tr>
                </thead>

                <tbody>
                {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ cp.product.name }}</td>
                        <td>{{ cp.rate }}</td>
                        <td>{{ cp.quantity }}</td>
                        <td>{{ cp.subtotal }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total</th>
                    <th>$ {{ cart.total }}</th>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
        <div class="col-md-6">
            <h3><u>Checkout Form</u></h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-dark">Place order</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/create_user.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
	<title>eCommerce | Create User</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
		integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
		crossorigin="anonymous" referrerpolicy="no-referrer" />
	<style>
		    @import url(https://fonts.googleapis.com/css?family=Roboto:300);

        header .header {
            background-color: #fff;
            height: 45px;
        }

        header a img {
            width: 134px;
            margin-top: 4px;
        }

        .login-page {
            width: 360px;
            padding: 8% 0 0;
            margin: auto;
        }

        .login-page .form .login {
            margin-top: -31px;
            margin-bottom: 26px;
        }

        .form {
            position: relative;
            z-index: 1;
            background: whitesmoke;
            max-width: 360px;
            margin: 0 auto 100px;
            padding: 45px;
            text-align: center;
            box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
        }

        .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: snow;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        .form button {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background-color: darkgrey;
            background-image: linear-gradient(45deg, wheat, whitesmoke);
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }

        .form .message {
            margin: 15px 0 0;
            color: gainsboro;
            font-size: 12px;
        }

        .form .message a {
            color: lightgoldenrodyellow;
            text-decoration: none;
        }

        .container {
            position: relative;
            z-index: 1;
            max-width: 300px;
            margin: 0 auto;
        }

        body {
            background-color: white;
            background-image: linear-gradient(45deg, lightslategrey, whitesmoke);
            font-family: "Roboto", sans-serif;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
    </style>
</head>

<body>
<div class="login-page">
        <div class="form">
	<div class="signup-form">
		<form action="/examples/actions/confirmation.php" method="post">
			{% csrf_token %}
            <div class="login">
                <div class="login-header">
                    <h3><u>ADD USER</u></h3>
                </div>
            </div>
			<hr>
			<div class="form-group">
				<div class="row">
					<div class="col-xs-6"><input type="text" class="form-control first_name" name="first_name"
							placeholder="First Name" required="required">
						<p class="firsttest" style="font-weight: bold;color: red;"></p>
					</div>

					<div class="col-xs-6"><input type="text" class="form-control last_name" name="last_name"
							placeholder="Last Name" required="required"></div>
				</div>
			</div>
			<div class="form-group">
				<input type="email" class="form-control email" name="email" placeholder="Email" required="required">
				<p class="emailtest" style="font-weight: bold;color: red;"></p>
			</div>
			<div class="form-group">
				<input type="password" class="form-control password" name="password" placeholder="Password"
					required="required">
				<p class="passtest" style="font-weight: bold;color: red;"></p>
			</div>
			<div class="form-group">
				<input type="password" class="form-control confirm_password" name="confirm_password"
					placeholder="Confirm Password" required="required">
				<p class="conftest" style="font-weight: bold;color: red;"></p>
			</div>
			<div class="form-group">
			</div>
			<div class="form-group">
				<button type="button" id="bttn" class="btn btn-primary btn-lg">create user</button>
			</div>
		</form>
         <div class="d-flex justify-content-around align-items-center mb-4">
        <a href="display_user"> View Users !!</a><br>
    </div>
          <div class="d-flex justify-content-around align-items-center mb-4">
          <a href="adminpage"> Return to Home !!</a><br>
    </div>
	</div>
        </div>
</div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
	integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
	function IsEmail(email) {
		var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
		if (!regex.test(email)) {
			return false;
		} else {
			return true;
		}
	}
	$('#bttn').click(() => {
		$('.firsttest').text("")
		$('.emailtest').text("")
		$('.passtest').text("")
		$('.conftest').text("")
		var first_name = $('.first_name').val()
		var last_name = $('.last_name').val()
		var email = $('.email').val()
		var password = $('.password').val()
		var confirm_password = $('.confirm_password').val()
		var data = {
			'csrfmiddlewaretoken': '{{csrf_token}}',
			'email': email,
			'first_name': first_name,
			'last_name': last_name,
			'password': password
		}
		console.log(first_name)
		if (first_name == '') {
			$('.firsttest').text("First name field must not be empty")
		} else if (email == '') {
			$('.emailtest').text("Email field must not be empty")
		} else if (password == '') {
			$('.passtest').text("Password field must not be empty")
		} else if (IsEmail(email) == false) {
			$('.emailtest').text("Enter a valid Email")
		} else if (confirm_password != password) {
			$('.conftest').text("Mismatching passwords")
		}
		else {
			$.ajax({
				url: '/create_user',
				method: 'POST',
				data: data,
				dataType: 'json',
				success: (data) => {
					if (data.success) {
						alert('user created')
						window.location.replace('/adminpage')
					}
				}
			})
		}
	})
</script>

</html>

templates/mycart.html
{% extends 'base.html' %}

{% block content %}

    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>CART</title>
    <style>
        table{
            width: 98%;
            margin-top: 10px;
            margin-left: 10px;
            margin-right: 10px;
        }
    </style>
</head>
<body>

    <div style="overflow-x:auto;">
        <table>
            <tr>
                        <th>Sl NO</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                       <!-- <th>Subtotal</th>
                        <th>Action</th>-->
                    </tr>

             {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.name}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                      <td>
                          <a href="managecart/{{ cp.id }}?action=dcr" class="btn btn-warning"> - </a>
                          <a href="managecart/{{ cp.id }}?action=inc" class="btn btn-primary"> + </a>
                          <a href="managecart/{{ cp.id }}?action=rmv" class="btn btn-danger"> x </a>
                      </td>
                    </tr>
             {% endfor %}
            <tr>
                <th colspan="2" class="text-right">Total Price</th>
                <th>$ {{ cart.total }}</th>
                {% if cart.cartproduct_set.all %}
                    <th><a href="emptycart">Empty Cart</a></th>
                {% endif %}
            </tr>
            {% if cart.cartproduct_set.all %}
                <tr>
                    <th><a class="btn btn-dark" href="/home"> Home </a></th>
                </tr>
            {% endif %}
            {% if cart.cartproduct_set.all %}
                <tr>
                    <th><a class="btn btn-dark" href="checkout"> Checkout </a></th>
                </tr>
            {% endif %}
        </table>

</body>
</html>

{% endblock %}

templates/order_history.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eCommerce</title>
</head>

<body>

    <div style="overflow-x:auto;">
        <table>

            <tr>
                <th>My Orders</th>
            </tr>

            <tr>
                <th>Ordered By</th>
                <th>Shipping Address</th>
                <th>Mobile</th>
                <th>Email</th>
                <th>Subtotal</th>
                <th>Order Status</th>
                <th>Payment Method</th>
                <th>Ordered At</th>
            </tr>
            {% for order in orders %}
            <tr>
                <td>{{ order.ordered_by }}</td>
                <td>{{ order.shipping_address}}</td>
                <td>{{ order.mobile }}</td>
                <td>{{ order.email }}</td>
                <td>{{ order.subtotal }}</td>
                <td>{{ order.order_status }}</td>
                <td>{{ order.payment_method }}</td>
                <td>{{ order.created_at}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="d-flex justify-content-around align-items-center mb-4">
        <a href="/home"> Return to Home !!</a><br>
    </div>
    
</body>

</html>

{% endblock %}